// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260817194153_AddSearchIndexes")]
    partial class AddSearchIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.FileResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AverageExcecutionTime")
                        .HasColumnType("integer");

                    b.Property<float>("AverageValue")
                        .HasColumnType("real");

                    b.Property<int>("DeltaSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("FirstExecutionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("MaximumValue")
                        .HasColumnType("real");

                    b.Property<float>("MedianValue")
                        .HasColumnType("real");

                    b.Property<float>("MinimumValue")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("AverageExcecutionTime");

                    b.HasIndex("AverageValue");

                    b.HasIndex("FileName")
                        .IsUnique();

                    b.HasIndex("FirstExecutionTime");

                    b.ToTable("Results", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ValueRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExceutionTime")
                        .HasColumnType("integer");

                    b.Property<Guid>("FileResultId")
                        .HasColumnType("uuid");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("FileResultId", "Date")
                        .IsDescending(false, true);

                    b.ToTable("Values", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ValueRecord", b =>
                {
                    b.HasOne("Domain.Entities.FileResult", "FileResult")
                        .WithMany("Values")
                        .HasForeignKey("FileResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileResult");
                });

            modelBuilder.Entity("Domain.Entities.FileResult", b =>
                {
                    b.Navigation("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
